### ISSUE TITLE
Caching Expiration per Typ festlegen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/experimental#12]
Ein Typ könnte festlegen ob die Dateien nur kurz oder lang gehalten werden sollen. Einige Dateien der Quellen ändern sich fast nie oder sie sind so groß dass sie besser regelmäßig gelöscht werden sollen. Die Typen könnten im Backend definiert werden.

**Comment by staabm** [comment]
Duplikat von https://github.com/FriendsOfREDAXO/experimental/issues/4 und https://github.com/FriendsOfREDAXO/experimental/issues/7
